import { IThemes } from "./interfaces";

export const monacoThemes: IThemes = {
  active4d: "Active4D",
  "all-hallows-eve": "All Hallows Eve",
  amy: "Amy",
  "birds-of-paradise": "Birds of Paradise",
  blackboard: "Blackboard",
  "brilliance-black": "Brilliance Black",
  "brilliance-dull": "Brilliance Dull",
  "chrome-devtools": "Chrome DevTools",
  clouds: "Clouds",
  "clouds-midnight": "Clouds Midnight",
  cobalt: "Cobalt",
  cobalt2: "Cobalt2",
  dawn: "Dawn",
  dracula: "Dracula",
  dreamweaver: "Dreamweaver",
  eiffel: "Eiffel",
  "espresso-libre": "Espresso Libre",
  github: "GitHub",
  idle: "IDLE",
  idlefingers: "idleFingers",
  iplastic: "iPlastic",
  katzenmilch: "Katzenmilch",
  krtheme: "krTheme",
  "kuroir-theme": "Kuroir Theme",
  lazy: "LAZY",
  "magicwb--amiga-": "MagicWB (Amiga)",
  merbivore: "Merbivore",
  "merbivore-soft": "Merbivore Soft",
  monoindustrial: "monoindustrial",
  monokai: "Monokai",
  "monokai-bright": "Monokai Bright",
  "night-owl": "Night Owl",
  "oceanic-next": "Oceanic Next",
  "pastels-on-dark": "Pastels on Dark",
  "slush-and-poppies": "Slush and Poppies",
  "solarized-dark": "Solarized-dark",
  "solarized-light": "Solarized-light",
  spacecadet: "SpaceCadet",
  sunburst: "Sunburst",
  "textmate--mac-classic-": "Textmate (Mac Classic)",
  tomorrow: "Tomorrow",
  "tomorrow-night": "Tomorrow-Night",
  "tomorrow-night-blue": "Tomorrow-Night-Blue",
  "tomorrow-night-bright": "Tomorrow-Night-Bright",
  "tomorrow-night-eighties": "Tomorrow-Night-Eighties",
  twilight: "Twilight",
  "upstream-sunburst": "Upstream Sunburst",
  "vibrant-ink": "Vibrant Ink",
  "xcode-default": "Xcode_default",
  zenburnesque: "Zenburnesque",
};
